### ISSUE TITLE
How to set config / env vars?

### ISSUE THREAD

**Issue by rsweetland** [microapps/MoonMail#15]
First, this project is fantastic. Thank you @davidgf and @alexandresaiz for the great work, and to the Microapps team for open sourcing it! 

I'm a bit new to the Serverless world and I'm not sure how magical the install process should be. Are the env / config variables supposed to be auto-set based on the newly created resources?

I'm using Serverless 0.5.5

My ```serverless init``` indicates I have several undefined variables (See below). 

```
sls project init
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'


Serverless: Initializing Serverless Project...  
Serverless: Enter a new stage name for this project:  (dev) prod
Serverless: For the "prod" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
Serverless: Select a profile for your project: 
  > serverless-dev-profile
Serverless: Creating stage "prod"...  
Serverless: Select a new region for your stage: 
  > us-east-1
    us-west-2
    eu-west-1
    eu-central-1
    ap-northeast-1
Serverless: Creating region "us-east-1" in stage "prod"...  
Serverless: WARNING: This variable is not defined: recipientsImportBucket  
Serverless: WARNING: This variable is not defined: account-id  
Serverless: WARNING: This variable is not defined: account-id  
Serverless: Deploying resources to stage "prod" in region "us-east-1" via Cloudformation (~3 minutes)...  
Serverless: \ Serverless: WARNING: This variable is not defined: opensStreamName  
Serverless: WARNING: This variable is not defined: clicksStreamName  
Serverless: WARNING: This variable is not defined: recipientsImportBucket  
Serverless: WARNING: This variable is not defined: clicksStreamName  
Serverless: WARNING: This variable is not defined: clicksStreamARN  
Serverless: WARNING: This variable is not defined: opensStreamName  
Serverless: WARNING: This variable is not defined: opensStreamARN  
Serverless: WARNING: This variable is not defined: attachRecipientsTopicARN  
Serverless: WARNING: This variable is not defined: apiHost  
Serverless: WARNING: This variable is not defined: sendCampaignTopicARN  
Serverless: WARNING: This variable is not defined: sendEmailsTopicARN  
Serverless: WARNING: This variable is not defined: recipientsImportBucket  
Serverless: WARNING: This variable is not defined: account-id  
Serverless: WARNING: This variable is not defined: account-id  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [ClicksStream, ListsTable, RecipientsTable, SendEmailsTopic, PrecompileCampaignTopic, PrecompileEmailTopic, AttachRecipientsTopic, LinksTable, OpensStream, IamRoleLambda]. . Delete requested by user.
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at ResourcesDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:242:25)
    at ResourcesDeploy.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by davidgf** [comment]
Hi @rsweetland. Thanks for your interest in MoonMail, we're glad you want to give it a go!
First thing you should do is removing DynamoDB tables that could be created when you did `sls project init` (if you don't remove them and try to deploy resources, Cloud Formation will fail again). After that, do `sls project init -c`, go to `_meta/variables/s-variables-stage.json` and define `account-id` (it must be set with the id of the AWS account you'll deploy to) and `recipientsImportBucket` (simply a bucket name, it doesn't matter the name you pick). Then you can continue with the install steps. Feel free to ask any other question in our [Gitter chat room](https://gitter.im/microapps/MoonMail)!

**Comment by rsweetland** [comment]
Thanks @davidgf! Got it working, and I saw the updated readme as well reflecting your instructions here.

A few notes that may help others:

* ```npm install``` needs to be run in project root, and in ```/events``` and and ``/api`` directories.
* Before ```sls function deploy``` would run, I had to set a dummy value for ```apiHost``` in s-variables-stage.json

With those few changes, I was able to get up and running! Now for some Postman tinkering.

Looks like the PR from @Alua-Kinzhebayeva may eliminate the S3 bucket creation step.

Of note: Happy to issue PR, but saw the readme change diverged from develop. Let me know if you want me to do that, PR from master for this one, or I can just let this lie.

**Comment by davidgf** [comment]
Thanks @rsweetland! We're glad you want to contribute. We'll accept PR from `master` that affect only the README.

**Comment by luctus** [comment]
I'm new to the serverless too, but it looks promising and so your project. Thank you very much for publishing it!

I faced the same problem reported by @rsweetland, but I have 3 different files in my `_meta/variables` folder:
```
s-variables-common.json
s-variables-dev-useast1.json
s-variables-dev.json
```

Should I add the `account-id` and the `recipientsImportBucket` keys to the three of them? Anyway, I added them and I got this error now:

```
$ sls resources deploy
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: Deploying resources to stage "dev" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: \ Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: opensStreamName
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: clicksStreamName
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: recipientsImportS3BucketName
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: clicksStreamName
Serverless: WARNING: This variable is not defined: clicksStreamARN
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: opensStreamName
Serverless: WARNING: This variable is not defined: opensStreamARN
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: attachRecipientsTopicARN
Serverless: WARNING: This variable is not defined: apiHost
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: sendCampaignTopicARN
Serverless: WARNING: This variable is not defined: sendEmailsTopicARN
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
Serverless: WARNING: This variable is not defined: region
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [PrecompileCampaignTopic, SendCampaignTopic, PrecompileEmailTopic, AttachRecipientsTopic, ClicksStream, FreeUsersSendEmailQueue, IamRoleLambda, RecipientsTable, LinksTable, ListsTable, OpensStream, SendEmailsTopic, RecipientsImportS3Bucket]. . Delete requested by user.
```

Am I missing some point? Thank you in advance.

**Comment by davidgf** [comment]
@luctus we've just updated the README with more detailed instructions. One thing that could help you debugging resources deployment errors is to apply the flag `--debug` to the `serverless resources deploy` command. Also, it's quite handy to check the Cloud Formation stack you are deploying in the AWS web console, as you can see the whole process of resources creation. Anyway, you are probably getting that error because you tried to deploy before and it failed. However, even though it failed, the DynamoDB tables weren't removed from your AWS account. So, if you try to deploy again, Cloud Formation fails, as some of the resources already exist. What you should do is removing those DynamoDB tables in your AWS account and try again. If you find any other problem or just want to say hi, we encourage you to join our [Gitter chat room](https://gitter.im/microapps/MoonMail) 😄
