### ISSUE TITLE
sls resources deploy issues

### ISSUE THREAD

**Issue by 262media** [microapps/MoonMail#263]
I can't find any documentation that might help me  to define these variables:

Serverless: WARNING: This variable is not defined: publicApiARN  
Serverless: WARNING: This variable is not defined: awsMarketplaceUserArn  
Serverless: WARNING: This variable is not defined: opensReportRCU

**Comment by 262media** [comment]
also got these warnings in the log:
```
Serverless: \ Serverless: WARNING: This variable is not defined: updateCampaignTopicARN  
Serverless: WARNING: This variable is not defined: attachSenderTopicARN  
Serverless: WARNING: the following template is requested but not defined: campaignsArchivedIndex in listCampaigns  
Serverless: WARNING: This variable is not defined: precompileCampaignTopicARN  
Serverless: WARNING: This variable is not defined: defaultApiKey  
Serverless: WARNING: This variable is not defined: defaultApiSecret  
Serverless: WARNING: This variable is not defined: defaultRegion  
Serverless: WARNING: This variable is not defined: defaultEmailAddress  
Serverless: WARNING: This variable is not defined: beeEditorClientId  
Serverless: WARNING: This variable is not defined: beeEditorClientSecret  
Serverless: WARNING: This variable is not defined: opensStreamName  
Serverless: WARNING: This variable is not defined: clicksStreamName  
Serverless: WARNING: This variable is not defined: defaultApiKey  
Serverless: WARNING: This variable is not defined: defaultApiSecret  
Serverless: WARNING: This variable is not defined: defaultRegion  
Serverless: WARNING: This variable is not defined: defaultEmailAddress  
Serverless: WARNING: This variable is not defined: unsubscribedRecipientTopicARN  
Serverless: WARNING: This variable is not defined: unsubscribedCallbackUrl  
Serverless: WARNING: This variable is not defined: eventsStreamARN  
Serverless: WARNING: This variable is not defined: apiHost  
Serverless: WARNING: This variable is not defined: sentEmailsTopicARN  
Serverless: WARNING: This variable is not defined: eventsStreamName  
Serverless: WARNING: This variable is not defined: attachRecipientsCountTopicARN  
Serverless: WARNING: This variable is not defined: iotEndpoint  
Serverless: WARNING: This variable is not defined: updateCampaignTopicARN  
Serverless: WARNING: This variable is not defined: clicksTableStreamARN  
Serverless: WARNING: This variable is not defined: attachRecipientsTopicARN  
Serverless: WARNING: This variable is not defined: updateCampaignTopicARN  
Serverless: WARNING: This variable is not defined: apiHost  
Serverless: WARNING: This variable is not defined: iotEndpoint  
Serverless: WARNING: This variable is not defined: iotEndpoint  
Serverless: WARNING: This variable is not defined: precompileEmailTopicARN  
Serverless: WARNING: This variable is not defined: redisEndpointPort  
Serverless: WARNING: This variable is not defined: redisEndpointAddress  
Serverless: WARNING: This variable is not defined: redisPassword  
Serverless: WARNING: This variable is not defined: attachListRecipientsTopicARN  
Serverless: WARNING: This variable is not defined: attachSegmentRecipientsTopicARN  
Serverless: WARNING: This variable is not defined: sendEmailsTopicARN  
Serverless: WARNING: This variable is not defined: updateCampaignTopicARN  
Serverless: WARNING: This variable is not defined: recipientsImportS3BucketName  
Serverless: WARNING: This variable is not defined: iotEndpoint  
Serverless: WARNING: This variable is not defined: updateListImportStatusTopicARN  
Serverless: WARNING: This variable is not defined: recipientsTableStreamARN  
Serverless: WARNING: This variable is not defined: clicksTableStreamARN  
Serverless: WARNING: This variable is not defined: opensTableStreamARN  
Serverless: WARNING: This variable is not defined: sentEmailsTopicARN  
Serverless: WARNING: This variable is not defined: clicksTableStreamARN  
Serverless: WARNING: This variable is not defined: opensTableStreamARN  
Serverless: WARNING: This variable is not defined: sentEmailsTableStreamARN  
Serverless: WARNING: This variable is not defined: clicksStreamARN  
Serverless: WARNING: This variable is not defined: opensStreamARN  
Serverless: WARNING: This variable is not defined: sendCampaignTopicARN  
Serverless: WARNING: This variable is not defined: sendEmailsTopicARN  
Serverless: WARNING: This variable is not defined: apiHost  
Serverless: WARNING: This variable is not defined: sentEmailsTopicARN  
Serverless: WARNING: This variable is not defined: emailNotificationsTopicARN  
Serverless: WARNING: This variable is not defined: apiHost  
Serverless: WARNING: This variable is not defined: clicksTableStreamARN  
Serverless: WARNING: This variable is not defined: opensTableStreamARN  
Serverless: WARNING: This variable is not defined: esHost  
Serverless: WARNING: This variable is not defined: esRegion  
Serverless: WARNING: This variable is not defined: esHost  
Serverless: WARNING: This variable is not defined: esRegion  
Serverless: WARNING: This variable is not defined: recipientsTableStreamARN  
Serverless: WARNING: This variable is not defined: esHost  
Serverless: WARNING: This variable is not defined: esRegion  
Serverless: WARNING: This variable is not defined: precompileEmailTopicARN  
Serverless: WARNING: This variable is not defined: esHost  
Serverless: WARNING: This variable is not defined: esRegion  
Serverless: WARNING: This variable is not defined: esHost  
Serverless: WARNING: This variable is not defined: esRegion  
Serverless: WARNING: This variable is not defined: publicApiARN  
Serverless: WARNING: This variable is not defined: awsMarketplaceUserArn  
Serverless: WARNING: This variable is not defined: opensReportRCU  
Serverless: WARNING: This variable is not defined: projectBucket  
Serverless: WARNING: This variable is not defined: publicApiARN  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [ScheduledEmailsTable, ListExportS3Bucket, AttachSenderTopic, PrecompileCampaignTopic, SentEmailsTable, SendCampaignTopic, PrecompileEmailTopic, AttachRecipientsTopic, ClicksStream, SentEmailsTopic, ListSegmentsTable, CampaignsTable, TemplatesTable, AttachSegmentRecipientsTopic, UsersTable, EventsBusTopic, IamRoleLambda, AttachListRecipientsTopic, RecipientsTable, StaticDataBucket, AutomationActionsTable, ClicksReportTable, UnsubscribedRecipientTopic, PaymentLogsTable, LinksTable, UpdateListImportStatusTopic, ExpertsTable, EmailAdminsTopic, ClicksTable, UpdateUserReputationTopic, ListsTable, EmailNotificationsTopic, AttachRecipientsCountTopic, OpensStream, EventsStream, UpdateCampaignTopic, SendEmailsTopic, OpensTable, OpensReportTable, RecipientsImportS3Bucket, ReportsTable]. . Delete requested by user.
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at ResourcesDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:241:25)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:236:23
From previous event:
    at ResourcesDeploy._deployResources (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:158:12)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:72:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

```
Is this a bug or am I missing something?? if this is the case what am i doing wrong??

thanks in advance 
and props for this great project

**Comment by 262media** [comment]
also from cloud formation:


```
01:47:13 UTC+0000 | CREATE_FAILED | AWS::S3::Bucket | StaticDataBucket | Resource creation cancelled
-- | -- | -- | -- | --
  | 01:47:12 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | UnsubscribedRecipientTopic | Resource creation cancelled
  | 01:47:12 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | AttachListRecipientsTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | UpdateUserReputationTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | UpdateCampaignTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | EmailNotificationsTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | PrecompileEmailTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::Kinesis::Stream | ClicksStream | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | UpdateListImportStatusTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SQS::Queue | AwsMarketplaceNotificationsQueue | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::IAM::Role | IamRoleLambda | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | AttachRecipientsCountTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::S3::Bucket | ListExportS3Bucket | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | AttachSenderTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SQS::Queue | FreeUsersSendEmailQueue | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | SendCampaignTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::S3::Bucket | RecipientsImportS3Bucket | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | AttachRecipientsCountTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | UpdateListImportStatusTopic |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | AttachRecipientsTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::SNS::Topic | SentEmailsTopic | Resource creation cancelled
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::Kinesis::Stream | ClicksStream |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | PaymentLogsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | PrecompileEmailTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | UpdateCampaignTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::S3::Bucket | ListExportS3Bucket |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | UpdateUserReputationTopic |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ListsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | AttachSenderTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | SentEmailsTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | UnsubscribedRecipientTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::IAM::Role | IamRoleLambda |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ScheduledEmailsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | EmailNotificationsTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | SendCampaignTopic |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SQS::Queue | FreeUsersSendEmailQueue |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::S3::Bucket | RecipientsImportS3Bucket |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SQS::Queue | AwsMarketplaceNotificationsQueue |  
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | AttachListRecipientsTopic |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | CampaignsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | AutomationsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::S3::Bucket | StaticDataBucket |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | UsersTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | SentEmailsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_IN_PROGRESS | AWS::SNS::Topic | AttachRecipientsTopic |  
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ListSegmentsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | OpensReportTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | AutomationActionsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | LinksTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | OpensTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | RecipientsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:11 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ReportsTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:10 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ClicksTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:10 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | TemplatesTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:10 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ClicksReportTable | Encountered non numeric value for property ReadCapacityUnits
  | 01:47:10 UTC+0000 | CREATE_FAILED | AWS::DynamoDB::Table | ExpertsTable | Encountered non numeric value for property ReadCapacityUnits

```

**Comment by davidgf** [comment]
Hi @262media, thanks for your interest in MoonMail! Before deploying resources, you should fill in your `s-variables-<stage>.json` with the following variables

```javascript
{
  "apiHost": "<api-gateway-url>", // You'll get this one after deploying an endpoint
  "defaultRegion": "us-east-1",
  "clicksRCU": 1,
  "clicksReportRCU": 1,
  "clicksReportWCU": 1,
  "clicksWCU": 1,
  "defaultRCU": 1,
  "defaultWCU": 1,
  "opensRCU": 1,
  "opensReportRCU": 1,
  "opensReportWCU": 1,
  "opensWCU": 1,
  "recipientsRCU": 1,
  "recipientsWCU": 1,
  "scheduledAtIndexRCU": 1,
  "scheduledAtIndexWCU": 1,
  "scheduledCampaignsRCU": 1,
  "scheduledCampaignsWCU": 1,
  "sentEmailsRCU": 1,
  "sentEmailsWCU": 1,
  "campaignsRCU": 1,
  "campaignsWCU": 1,
  "usersRCU": 1,
  "recipientsIndexesWCU": 1,
  "listsRCU": 1,
  "listsWCU": 1,
  "defaultApiKey": "<aws-api-key>",
  "defaultApiSecret": "<aws-api-secret>",
  "defaultEmailAddress": "david.garcia@microapps.com",
  "defaultFromName": "David",
  "stage": "dev"
}
```
They mainly set the read and write capacity units for DynamoDB tables. Beware that even though your first attempt of deploying resources failed, some of them (DynamoDB tables, S3 buckets, etc.) could still exist in your AWS account, so you should delete them before.

I hope it helps!

**Comment by 262media** [comment]
sorry for the late reply @davidgf and thank you for your time. I'll test again soon.  Regards

**Comment by aspiers** [comment]
I still didn't see an answer for this question:

[**@262media**](https://github.com/262media) commented on [28 Jan 2018, 01:35 GMT](https://github.com/microapps/MoonMail/issues/263#issue-292168559 "2018-01-28T01:35:03Z - Replied by Github Reply Comments"):
> I can't find any documentation that might help me  to define these variables:
> 
> Serverless: WARNING: This variable is not defined: publicApiARN  
> 
> Serverless: WARNING: This variable is not defined: awsMarketplaceUserArn  
> 
> Serverless: WARNING: This variable is not defined: opensReportRCU

and indeed after guessing a value for publicApiARN my deployment is failing due to awsMarketplaceUserArn.

**Comment by aspiers** [comment]
Finally managed to guess values for these:

```
    "publicApiARN": "arn:aws:apigateway:eu-west-2::*",
    "awsMarketplaceUserArn": "arn:aws:iam::0123456789012:user/moonmail",
```

where the User ARN came from creating a `moonmail` user in the IAM console and pasting in the exact ARN.

**Comment by sheerun** [comment]
@davidgf This doesn't list awsMarketplaceUserArn which seems to be required. The deployment of resources failed in my case with:

```
The following resource(s) failed to create: [AwsMarketplaceNotificationsQueuePolicy, ListSegmentsTable, AutomationActionsTable, ClicksReportTable, OpensReportTable, ReportsTable]. . Delete requested by user.
```

**Comment by amitprince** [comment]
@davidgf  after putting all the variables in the s-stage .json ..,when I put the command sls resources Deploy i am getting this error ..

$ sls resources deploy
SyntaxError: Unexpected token }
F:\New folder (3)\MoonMail\node_modules\bluebird\js\release\async.js:62
      }
      ^

SyntaxError: Unexpected token }
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (F:\New folder (3)\MoonMail\node_modules\bluebird\js\release\promise.js:31:13)
    at Object.<anonymous> (F:\New folder (3)\MoonMail\node_modules\bluebird\js\release\bluebird.js:9:36)
From previous event:
    at Serverless.init (C:\Users\Amit nayak\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:72:25)
    at Object.<anonymous> (C:\Users\Amit nayak\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless:17:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
