### ISSUE TITLE
not clear what to set publicApiARN to

### ISSUE THREAD

**Issue by aspiers** [microapps/MoonMail#326]
`s-templates.json` contains this fragment which relies on the `publicApiARN` variable being set:

```
  "apiGatewayStatementTemplate": {
    "Effect": "Allow",
    "Action": [
      "apigateway:POST",
      "apigateway:DELETE"
    ],
    "Resource": [
      "${publicApiARN}"
    ]
  },
```

If you don't set it, deploying the CF stack via `sls resources deploy` fails with:

```
19:49:11 UTC+0100 | CREATE_FAILED | AWS::IAM::Policy | IamPolicyLambda | Resource ${publicApiARN} must be in ARN format or "*".
-- | -- | -- | -- | --
```

and a near useless stack-trace:

```
Serverless: |   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +6s                                      
Serverless: -   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: \   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: /   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: -   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: |   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: /   serverless:lib.actions.ResourcesDeploy CF stack status:  CREATE_IN_PROGRESS +5s                                      
Serverless: \   serverless:lib.actions.ResourcesDeploy CF stack status:  DELETE_IN_PROGRESS +5s                                      
/home/adam/.config/yarn/global/node_modules/bluebird/js/release/async.js:61                                                          
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: undefined
    at new ServerlessError (/home/adam/.config/yarn/global/node_modules/serverless/lib/Error.js:17:11)
    at ResourcesDeploy.<anonymous> (/home/adam/.config/yarn/global/node_modules/serverless/lib/actions/ResourcesDeploy.js:241:25)
From previous event:
    at /home/adam/.config/yarn/global/node_modules/serverless/lib/actions/ResourcesDeploy.js:236:23
From previous event:
    at ResourcesDeploy._deployResources (/home/adam/.config/yarn/global/node_modules/serverless/lib/actions/ResourcesDeploy.js:158:12)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/home/adam/.config/yarn/global/node_modules/serverless/lib/actions/ResourcesDeploy.js:72:12)
From previous event:
    at /home/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /home/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/home/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/home/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/home/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:398:38)
    at /home/adam/.config/yarn/global/node_modules/serverless/bin/serverless:19:16
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.<anonymous> (/home/adam/.config/yarn/global/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

Admittedly, serverless does give a warning about it just before that:

```
Serverless: WARNING: This variable is not defined: publicApiARN                                                                      
```

but this is drowned out by about 30 other near identical warnings.

Unfortunately it is not documented anywhere what to set this to, therefore I can't imagine how anyone other than an AWS / CloudFormation / MoonMail expert could ever successfully figure out how to deploy MoonMail themselves.

So what should it be set to?

This same question was asked on StackOverflow a few months ago but (rather unfairly IMHO) got 2 downvotes and was deleted:

- https://stackoverflow.com/questions/48795483/what-should-publicapiarn-be-set-to

N.B. IIUC you need >10k reputation on StackOverflow to view this since it was deleted, so here's a screenshot:

![publicapiarn](https://user-images.githubusercontent.com/100738/39942795-8851a3fe-5558-11e8-9402-524c4b0d506e.png)

**Comment by aspiers** [comment]
Thanks a lot!  I'll submit a PR for this.
